services:
  - type: web
    name: publisher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: publisher-cache
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    regions:
      - frankfurt
    plan: starter

  - type: redis
    name: publisher-cache
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction 