services:
  - type: web
    name: publisher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: 0
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
    autoDeploy: true 