services:
  - type: web
    name: publisher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py --worker-class eventlet dashboard:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: 0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: WEB_CONCURRENCY
        value: 4
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    domains:
      - publisher.onrender.com 